#ifndef MICROEDEN_SECRETS_H
#define MICROEDEN_SECRETS_H
#define SECRET_WIFI_SSID "YOUR_WIFI_SSID"
#define SECRET_WIFI_PASSWORD "YOUR_WIFI_PASSWORD"
#define SECRET_DEVICE_ID "YOUR_DEVICE_ID"
#define SECRET_DEVICE_TOKEN "YOUR_DEVICE_TOKEN"
#endif
